# Site settings
baseurl = "https://example.org/"
themesDir = "../.." # When copied to your root folder use ./themes
languageCode = "en-us"
title = "Windener Theme"
theme = "windener"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[params]
  name = "John Doe"
  description = "Describe your website"
  bio = "Blogger & Programmer"
  email = "johndoe@provider.com"
  profile = "https://about.me/example" # Link to your profile here
  enableRSS = true
  favicon = "" # A favicon file located in your static directory
  logo = "" # Logo located in static directory

# Add additional social link entries underneath
[social]
  facebook = "https://www.facebook.com/"
  twitter  = "https://www.twitter.com/"
  github   = "https://www.github.com/"
  dribbble  = "https://www.dribbble.com/"
  codepen  = "https://www.codepen.io/"
  behance  = "https://www.behance.net/"
  stackoverflow  = "https://www.stackoverflow.com/"
  pinterest  = "https://www.pinterest.com/"
  instagram  = "https://www.instagram.com/"
  linkedin  = "https://www.linkedin.com/"
